[package]
name = "dart-typegen"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive", "string"] }
insta = "1.43.1"
miette = { version = "7.6.0", features = ["fancy", "syntect-highlighter"] }
knus = "3.3.1"
convert_case = "0.8.0"
thiserror = "2.0.12"
